# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\any12\PycharmProjects\phone_book\edit_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QLineEdit, QMessageBox
from PyQt5.QtCore import QDate, Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(283, 203)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 241, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NamelineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.NamelineEdit.setObjectName("NamelineEdit")
        self.verticalLayout.addWidget(self.NamelineEdit)
        self.TelephonelineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.TelephonelineEdit.setObjectName("TelephonelineEdit")
        self.verticalLayout.addWidget(self.TelephonelineEdit)
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.OkpushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.OkpushButton.setObjectName("OkpushButton")
        self.horizontalLayout.addWidget(self.OkpushButton)
        self.CancelpushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.CancelpushButton.setObjectName("CancelpushButton")
        self.horizontalLayout.addWidget(self.CancelpushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OkpushButton.setText(_translate("MainWindow", "PushButton"))
        self.CancelpushButton.setText(_translate("MainWindow", "PushButton"))

class Edit_Window(QMainWindow, Ui_MainWindow):
    switch_window = QtCore.pyqtSignal(str)

    def __init__(self):
        QMainWindow.__init__(self)
        self.setupUi(self)
        self.widgets_adjust()
        self.setWindowTitle("Изменение контакта")
        self.setMinimumWidth(290)
        self.setMaximumWidth(290)

    def widgets_adjust(self):
        # init NamelineEdit parameters
        self.NamelineEdit.setPlaceholderText("Имя контакта")
        self.NamelineEdit.setStyleSheet("font-size: 12px;")
        # init TelephonelineEdit parameters
        self.TelephonelineEdit.setPlaceholderText("Новый телефон")
        self.TelephonelineEdit.setStyleSheet("font-size: 12px;")
        # init dateEdit parameters
        self.dateEdit.setStyleSheet("font-size: 12px;")
        self.dateEdit.setDate(QDate.currentDate())
        # init OkpushButton parameters
        self.OkpushButton.setText("Ок")
        self.OkpushButton.setMinimumHeight(30)
        self.OkpushButton.setMinimumWidth(60)
        self.OkpushButton.setStyleSheet("border-radius: 8px;"
                                        "color: #000000;"
                                        "background: #d4d2d6;"
                                        "font-size: 12px;"
                                        "border-bottom: 3px solid #b9b5bd;")
        # init CancelpushButton parameters
        self.CancelpushButton.setText("Отмена")
        self.CancelpushButton.setMinimumHeight(30)
        self.CancelpushButton.setMinimumWidth(60)
        self.CancelpushButton.setStyleSheet("border-radius: 8px;"
                                            "color: #000000;"
                                            "background: #d4d2d6;"
                                            "font-size: 12px;"
                                            "border-bottom: 3px solid #b9b5bd;")

        # actions when buttons & checkbox clicked
        self.OkpushButton.clicked.connect(self.clicked_ok_b)
        self.CancelpushButton.clicked.connect(self.clicked_c_b)

    def click_button(self, label):
        print('The \"', label, '\" button is pressed!')

    def clicked_ok_b(self):
        self.click_button(self.OkpushButton.text())
        if self.NamelineEdit.text() and self.TelephonelineEdit.text():
            self.switch_window.emit("edit -> 4")
        else:
            m = QMessageBox()  # init
            m.setWindowTitle("Ошибка заполнения")  # set title
            m.setText("Необходимо заполнить все поля!")
            m.setIcon(QMessageBox.Critical)  # set icon
            m.setStandardButtons(QMessageBox.Ok)
            m.exec_()

    def clicked_c_b(self):
        self.click_button(self.CancelpushButton.text())
        self.NamelineEdit.clear()
        self.TelephonelineEdit.clear()
        self.dateEdit.setDate(QDate.currentDate())
        self.switch_window.emit("edit -> 4")
