# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\any12\PycharmProjects\phone_book\pas_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(357, 314)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AddresslineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.AddresslineEdit.setObjectName("AddresslineEdit")
        self.verticalLayout.addWidget(self.AddresslineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ChangePasswordPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ChangePasswordPushButton.setObjectName("ChangePasswordPushButton")
        self.horizontalLayout.addWidget(self.ChangePasswordPushButton)
        self.CancelPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.CancelPushButton.setObjectName("CancelPushButton")
        self.horizontalLayout.addWidget(self.CancelPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ChangePasswordPushButton.setText(_translate("MainWindow", "PushButton"))
        self.CancelPushButton.setText(_translate("MainWindow", "PushButton"))
