# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\any12\PycharmProjects\phone_book\reg_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 534)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 441, 469))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NamelineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.NamelineEdit.setObjectName("NamelineEdit")
        self.verticalLayout.addWidget(self.NamelineEdit)
        self.PasswordlineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.PasswordlineEdit.setObjectName("PasswordlineEdit")
        self.verticalLayout.addWidget(self.PasswordlineEdit)
        self.RepeatlineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.RepeatlineEdit.setObjectName("RepeatlineEdit")
        self.verticalLayout.addWidget(self.RepeatlineEdit)
        self.DateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.DateEdit.setObjectName("DateEdit")
        self.verticalLayout.addWidget(self.DateEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.OkPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.OkPushButton.setObjectName("OkPushButton")
        self.horizontalLayout.addWidget(self.OkPushButton)
        self.CancelPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.CancelPushButton.setObjectName("CancelPushButton")
        self.horizontalLayout.addWidget(self.CancelPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OkPushButton.setText(_translate("MainWindow", "PushButton"))
        self.CancelPushButton.setText(_translate("MainWindow", "PushButton"))
