# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\any12\PycharmProjects\phone_book\reg_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.RepeatlineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.RepeatlineEdit.setObjectName("RepeatlineEdit")
        self.gridLayout.addWidget(self.RepeatlineEdit, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.OkPushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.OkPushButton.setObjectName("OkPushButton")
        self.horizontalLayout.addWidget(self.OkPushButton)
        self.CancelPushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.CancelPushButton.setObjectName("CancelPushButton")
        self.horizontalLayout.addWidget(self.CancelPushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.NamelineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.NamelineEdit.setObjectName("NamelineEdit")
        self.gridLayout.addWidget(self.NamelineEdit, 0, 0, 1, 1)
        self.PasswordlineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.PasswordlineEdit.setObjectName("PasswordlineEdit")
        self.gridLayout.addWidget(self.PasswordlineEdit, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.DatelineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.DatelineEdit.setObjectName("DatelineEdit")
        self.horizontalLayout_2.addWidget(self.DatelineEdit)
        self.DateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.DateEdit.setCalendarPopup(True)
        self.DateEdit.setObjectName("DateEdit")
        self.horizontalLayout_2.addWidget(self.DateEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OkPushButton.setText(_translate("MainWindow", "PushButton"))
        self.CancelPushButton.setText(_translate("MainWindow", "PushButton"))
